openapi: 3.1.0
info:
  x-publicVersion: true
  title: Management Webhooks
tags:
  - name: Merchant account
  - name: Payment Methods
x-staticResponse: response.json
webhooks:
  merchant.created:
    post:
      tags:
        - Merchant account
      summary: Merchant account created
      description: >-
        A merchant account [was
        created](https://docs.adyen.com/api-explorer/#/ManagementService/latest/post/merchants).
      x-addedInVersion: '1'
      operationId: post-merchant.created
      x-sortIndex: 1
      x-methodName: merchantAccountCreated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              merchant.created:
                $ref: '#/components/examples/post-merchant.created-merchant.created'
            schema:
              $ref: '#/components/schemas/MerchantCreatedNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                merchant.created:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/AccountNotificationResponse'
          description: OK - the request has succeeded.
  merchant.updated:
    post:
      tags:
        - Merchant account
      summary: Merchant account capability updated
      description: >-
        There were changes to the verification status and capabilities of a
        [merchant
        account](https://docs.adyen.com/api-explorer/#/ManagementService/latest/post/merchants).
        If the verification fails, this webhook includes the errors and the
        actions that you can take to resolve them.
      x-addedInVersion: '1'
      operationId: post-merchant.updated
      x-sortIndex: 2
      x-methodName: merchantAccountCapabilityUpdated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              merchant-updated-valid:
                $ref: >-
                  #/components/examples/post-merchant.updated-merchant-updated-valid
              merchant-updated-with-errors:
                $ref: >-
                  #/components/examples/post-merchant.updated-merchant-updated-with-errors
            schema:
              $ref: '#/components/schemas/MerchantUpdatedNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                merchant-updated-valid:
                  $ref: '#/components/examples/WebhookAck'
                merchant-updated-with-errors:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/AccountNotificationResponse'
          description: OK - the request has succeeded.
  paymentMethod.created:
    post:
      tags:
        - Payment method
      summary: Payment method created
      description: >-
        A request to [add a payment
        method](https://docs.adyen.com/api-explorer/Management/latest/post/merchants/_merchantId_/paymentMethodSettings)
        was completed.
      x-addedInVersion: '1'
      operationId: post-paymentMethod.created
      x-sortIndex: 1
      x-methodName: paymentMethodCreated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              paymentMethod.created:
                $ref: >-
                  #/components/examples/post-paymentMethod.created-paymentMethod.created
            schema:
              $ref: '#/components/schemas/PaymentMethodCreatedNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                paymentMethod.created:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/PaymentMethodNotificationResponse'
          description: OK - the request has succeeded.
  paymentMethod.requestRemoved:
    post:
      tags:
        - Payment method
      summary: Payment method request removed
      description: >-
        A request to add a payment method is removed. You must make another
        request to [add a payment
        method](https://docs.adyen.com/api-explorer/Management/latest/post/merchants/_merchantId_/paymentMethodSettings).
      x-addedInVersion: '2'
      operationId: post-paymentMethod.requestRemoved
      x-sortIndex: 3
      x-methodName: paymentMethodRequestRemoved
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              paymentMethod.requestRemoved:
                $ref: >-
                  #/components/examples/post-paymentMethod.requestRemoved-paymentMethod.requestRemoved
            schema:
              $ref: >-
                #/components/schemas/PaymentMethodRequestRemovedNotificationRequest
      responses:
        '200':
          content:
            application/json:
              examples:
                paymentMethod.requestRemoved:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/PaymentMethodNotificationResponse'
          description: OK - the request has succeeded.
  paymentMethod.requestScheduledForRemoval:
    post:
      tags:
        - Payment method
      summary: Payment method request scheduled for removal
      description: >-
        A request to [add a payment
        method](https://docs.adyen.com/api-explorer/Management/latest/post/merchants/_merchantId_/paymentMethodSettings)
        will be removed in 30 days. To make sure the payment method is added,
        provide the missing [KYC
        information](https://docs.adyen.com/marketplaces-and-platforms/collect-verification-details).
      x-addedInVersion: '2'
      operationId: post-paymentMethod.requestScheduledForRemoval
      x-sortIndex: 2
      x-methodName: paymentMethodRequestScheduledForRemoval
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              paymentMethod.requestScheduledForRemoval:
                $ref: >-
                  #/components/examples/post-paymentMethod.requestScheduledForRemoval-paymentMethod.requestScheduledForRemoval
            schema:
              $ref: >-
                #/components/schemas/PaymentMethodScheduledForRemovalNotificationRequest
      responses:
        '200':
          content:
            application/json:
              examples:
                paymentMethod.requestScheduledForRemoval:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/PaymentMethodNotificationResponse'
          description: OK - the request has succeede
