openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Payment API
tags:
  - name: Payments
  - name: Modifications
paths:
  /adjustAuthorisation:
    post:
      tags:
        - Change
        - The
        - Authorised
        - Amount
        - Authorization
      summary: Change the authorised amount
      description: >-
        Allows you to increase or decrease the authorised amount after the
        initial authorisation has taken place. This functionality enables for
        example tipping, improving the chances your authorisation will be valid,
        or charging the shopper when they have already left the merchant
        premises.


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).

        > If you have a [newer
        integration](https://docs.adyen.com/online-payments), and are doing:

        > * [Asynchronous
        adjustments](https://docs.adyen.com/online-payments/adjust-authorisation#asynchronous-or-synchronous-adjustment),
        use the
        [`/payments/{paymentPspReference}/amountUpdates`](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/{paymentPspReference}/amountUpdates)
        endpoint on Checkout API.

        > * [Synchronous
        adjustments](https://docs.adyen.com/online-payments/adjust-authorisation#asynchronous-or-synchronous-adjustment),
        use this endpoint.
  /authorise:
    post:
      tags:
        - Create
        - null
        - Authorization
        - Authorization
        - Authorization
      summary: Create an authorisation
      description: >-
        Creates a payment with a unique reference (`pspReference`) and attempts
        to obtain an authorisation hold. For cards, this amount can be captured
        or cancelled later. Non-card payment methods typically don't support
        this and will automatically capture as part of the authorisation.

        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments)
        endpoint under Checkout API instead.
  /authorise3d:
    post:
      tags:
        - Complete
        - Authorization
        - Authorization
        - Authorization
        - Authorization
      summary: Complete a 3DS authorisation
      description: >-
        For an authenticated 3D Secure session, completes the payment
        authorisation. This endpoint must receive the `md` and `paResponse`
        parameters that you get from the card issuer after a shopper pays via 3D
        Secure.


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/details`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments/details)
        endpoint under Checkout API instead.
  /authorise3ds2:
    post:
      tags:
        - Complete
        - S2
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Authorization
      summary: Complete a 3DS2 authorisation
      description: >-
        For an authenticated 3D Secure 2 session, completes the payment
        authorisation. This endpoint must receive the `threeDS2Token` and
        `threeDS2Result` parameters.


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce/3d-secure).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/details`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments/details)
        endpoint under Checkout API instead.
  /cancel:
    post:
      tags:
        - Cancel
        - null
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
      summary: Cancel an authorisation
      description: >-
        Cancels the authorisation hold on a payment, returning a unique
        reference for this request. You can cancel payments after authorisation
        only for payment methods that support distinct authorisations and
        captures.


        For more information, refer to
        [Cancel](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/cancel).


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/{paymentPspReference}/cancels`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments/{paymentPspReference}/cancels)
        endpoint under Checkout API instead.
  /cancelOrRefund:
    post:
      tags:
        - Cancel
        - Or
        - Refunds
        - Payments
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
      summary: Cancel or refund a payment
      description: >-
        Cancels a payment if it has not been captured yet, or refunds it if it
        has already been captured. This is useful when it is not certain if the
        payment has been captured or not (for example, when using auto-capture).


        Do not use this endpoint for payments that involve:
         * [Multiple partial captures](https://docs.adyen.com/online-payments/capture).
         * [Split data](https://docs.adyen.com/marketplaces-and-platforms/processing-payments#providing-split-information) either at time of payment or capture for Adyen for Platforms.

         Instead, check if the payment has been captured and make a corresponding [`/refund`](https://docs.adyen.com/api-explorer/#/Payment/refund) or [`/cancel`](https://docs.adyen.com/api-explorer/#/Payment/cancel) call.

        For more information, refer to [Cancel or
        refund](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/cancel-or-refund).


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/{paymentPspReference}/reversals`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments/{paymentPspReference}/reversals)
        endpoint under Checkout API instead.
  /capture:
    post:
      tags:
        - Capture
        - null
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
      summary: Capture an authorisation
      description: >+
        Captures the authorisation hold on a payment, returning a unique
        reference for this request. Usually the full authorisation amount is
        captured, however it's also possible to capture a smaller amount, which
        results in cancelling the remaining authorisation balance.


        Payment methods that are captured automatically after authorisation
        don't need to be captured. However, submitting a capture request on
        these transactions will not result in double charges. If immediate or
        delayed auto-capture is enabled, calling the capture method is not
        neccessary.


        For more information refer to
        [Capture](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/capture).


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/{paymentPspReference}/captures`](https://docs.adyen.com/api-explorer/#/CheckoutService/v67/post/payments/{paymentPspReference}/captures)
        endpoint on Checkout API instead.

  /donate:
    post:
      tags:
        - Create
        - Donations
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
      summary: Create a donation
      description: >-
        Schedules a new payment to be created (including a new authorisation
        request) for the specified donation using the payment details of the
        original payment.


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/donations`](https://docs.adyen.com/api-explorer/#/CheckoutService/latest/post/donations)
        endpoint under Checkout API instead.
  /getAuthenticationResult:
    post:
      tags:
        - Get
        - The
        - Authentication
        - Results
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
        - Authentication
        - Results
      summary: Get the 3DS authentication result
      description: >-
        Return the authentication result after doing a 3D Secure authentication
        only.
  /refund:
    post:
      tags:
        - Refunds
        - Captured
        - Payments
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
        - Authentication
        - Results
      summary: Refund a captured payment
      description: >-
        Refunds a payment that has previously been captured, returning a unique
        reference for this request. Refunding can be done on the full captured
        amount or a partial amount. Multiple (partial) refunds will be accepted
        as long as their sum doesn't exceed the captured amount. Payments which
        have been authorised, but not captured, cannot be refunded, use the
        /cancel method instead.


        Some payment methods/gateways do not support partial/multiple refunds.

        A margin above the captured limit can be configured to cover
        shipping/handling costs.


        For more information, refer to
        [Refund](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/refund).


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/payments/{paymentPspReference}/refunds`](https://docs.adyen.com/api-explorer/#/CheckoutService/payments/{paymentPspReference}/refunds)
        endpoint under Checkout API instead.
  /retrieve3ds2Result:
    post:
      tags:
        - Get
        - The
        - S2
        - Authentication
        - Results
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
        - Authentication
        - Results
      summary: Get the 3DS2 authentication result
      description: >-
        Retrieves the `threeDS2Result` after doing a 3D Secure 2 authentication
        only.
  /technicalCancel:
    post:
      tags:
        - Cancel
        - null
        - Authorization
        - Using
        - Your
        - References
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
        - Authentication
        - Results
      summary: Cancel an authorisation using your reference
      description: >-
        This endpoint allows you to cancel a payment if you do not have the PSP
        reference of the original payment request available.


        In your call, refer to the original payment by using the `reference`
        that you specified in your payment request.


        For more information, see [Technical
        cancel](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/cancel#technical-cancel). 


        > This endpoint is part of our [classic API
        integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce).
        If using a [newer integration](https://docs.adyen.com/online-payments),
        use the
        [`/cancels`](https://docs.adyen.com/api-explorer/#/CheckoutService/cancels)
        endpoint under Checkout API instead.
  /voidPendingRefund:
    post:
      tags:
        - Cancel
        - null
        - In-person
        - Refunds
        - Authorization
        - Authorization
        - Authorization
        - Authorization
        - Cancel
        - Or
        - Refunds
        - Capture
        - Donate
        - Authentication
        - Results
        - Pending
      summary: Cancel an in-person refund
      description: >-
        This endpoint allows you to cancel an unreferenced refund request before
        it has been completed.


        In your call, you can refer to the original refund request either by
        using the `tenderReference`, or the `pspReference`. We recommend
        implementing based on the `tenderReference`, as this is generated for
        both offline and online transactions.


        For more information, refer to [Cancel an unreferenced
        refund](https://docs.adyen.com/point-of-sale/re
