openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Payout API
tags:
  - name: Initialization
  - name: Reviewing
  - name: Instant payouts
paths:
  /confirmThirdParty:
    post:
      tags:
        - Confirm
        - Payouts
        - Third
        - Party
      summary: Confirm a payout
      description: |-
        Confirms a previously submitted payout.

        To cancel a payout, use the `/declineThirdParty` endpoint.
  /declineThirdParty:
    post:
      tags:
        - Cancel
        - Payouts
        - Third
        - Party
      summary: Cancel a payout
      description: |-
        Cancels a previously submitted payout.

        To confirm and send a payout, use the `/confirmThirdParty` endpoint.
  /payout:
    post:
      tags:
        - Make
        - null
        - Instant
        - Cards
        - Payouts
        - Third
        - Party
        - Payouts
      summary: Make an instant card payout
      description: >-
        With this call, you can pay out to your customers, and funds will be
        made available within 30 minutes on the cardholder's bank account (this
        is dependent on whether the issuer supports this functionality). Instant
        card payouts are only supported for Visa and Mastercard cards.
  /storeDetail:
    post:
      tags:
        - Store
        - Payouts
        - Details
        - Third
        - Party
        - Payouts
        - Detail
      summary: Store payout details
      description: >-
        Stores payment details under the `PAYOUT` recurring contract. These
        payment details can be used later to submit a payout via the
        `/submitThirdParty` call.
  /storeDetailAndSubmitThirdParty:
    post:
      tags:
        - Store
        - Details
        - And
        - Submit
        - Payouts
        - Third
        - Party
        - Payouts
        - Detail
        - And
        - Submit
      summary: Store details and submit a payout
      description: >-
        Submits a payout and stores its details for subsequent payouts.


        The submitted payout must be confirmed or declined either by a reviewer
        or via `/confirmThirdParty` or `/declineThirdParty` calls.
  /submitThirdParty:
    post:
      tags:
        - Submit
        - Payouts
        - Third
        - Party
        - Payouts
        - Detail
        - And
        - Submit
      summary: Submit a payout
      description: >-
        Submits a payout using the previously stored payment details. To store
        payment details, use the `/storeDetail` API call.


        The submitted payout must be confirmed or declined either by a reviewer
        or via `/confirmThirdPar
