openapi: 3.1.0
info:
  x-publicVersion: true
  title: Transfer webhooks
tags:
  - name: General
x-staticResponse: response.json
webhooks:
  balancePlatform.transfer.created:
    post:
      tags:
        - General
      summary: Transfer created
      description: Adyen sends this webhook when there are fund movements on your platform.
      x-addedInVersion: '1'
      operationId: post-balancePlatform.transfer.created
      x-sortIndex: 0
      x-methodName: transferCreated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
          description: OK - the request has succeeded.
  balancePlatform.transfer.updated:
    post:
      tags:
        - General
      summary: Transfer updated
      description: >+
        Adyen sends this webhook when the status of a transfer changes. Use the
        `data.id` to track the original transfer resource in the
        [balancePlatform.transfer.created](https://docs.adyen.com/api-explorer/transfer-webhooks/1/post/balancePlatform.transfer.created)
        webhook.


        The `status` field indicates the event that triggered the webhook. 

      x-addedInVersion: '1'
      operationId: post-balancePlatform.transfer.updated
      x-sortIndex: 0
      x-methodName: transferUpdated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
          description: OK - the request has succeede
