openapi: 3.1.0
info:
  x-publicVersion: true
  title: Transaction webhooks
x-groups:
  - General
tags:
  - name: General
x-staticResponse: response.json
webhooks:
  balancePlatform.transaction.created:
    post:
      tags:
        - General
      summary: Transaction created
      description: Adyen sends this webhook when there are new fund transfers.
      x-addedInVersion: '1'
      operationId: post-balancePlatform.transaction.created
      x-groupName: General
      x-sortIndex: 0
      x-methodName: transactionCreated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionNotificationRequestV4'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
          description: OK - the request has succeede
