openapi: 3.0.0
info:
  title: Stripe Application Secrets API
paths:
  /v1/apps/secrets:
    get:
      description: <p>List all secrets stored on the given scope.</p>
      tags:
        - Applications
        - Secrets
      summary: Retrieve Apps Secrets
    post:
      description: <p>Create or replace a secret in the secret store.</p>
      tags:
        - Applications
        - Secrets
      summary: Create Apps Secrets
  /v1/apps/secrets/delete:
    post:
      description: <p>Deletes a secret from the secret store by name and scope.</p>
      tags:
        - Applications
        - Secrets
      summary: Create Apps Secrets Delete
  /v1/apps/secrets/find:
    get:
      description: <p>Finds a secret in the secret store by name and
      tags:
        - Applications
        - Find
        - Secrets
      summary: Retrieve Apps Secrets Find
