openapi: 3.0.0
info:
  title: Stripe Coupons API
paths:
  /v1/coupons:
    get:
      description: <p>Returns a list of your coupons.</p>
      tags:
        - Coupons
      summary: Retrieve Coupons
    post:
      description: >-
        <p>You can create coupons easily via the <a
        href="https://dashboard.stripe.com/coupons">coupon management</a> page
        of the Stripe dashboard. Coupon creation is also accessible via the API
        if you need to create coupons on the fly.</p>


        <p>A coupon has either a <code>percent_off</code> or an
        <code>amount_off</code> and <code>currency</code>. If you set an
        <code>amount_off</code>, that amount will be subtracted from any
        invoice’s subtotal. For example, an invoice with a subtotal of
        <currency>100</currency> will have a final total of
        <currency>0</currency> if a coupon with an <code>amount_off</code> of
        <amount>200</amount> is applied to it and an invoice with a subtotal of
        <currency>300</currency> will have a final total of
        <currency>100</currency> if a coupon with an <code>amount_off</code> of
        <amount>200</amount> is applied to it.</p>
      tags:
        - Coupons
      summary: Create Coupons
  /v1/coupons/{coupon}:
    delete:
      description: >-
        <p>You can delete coupons via the <a
        href="https://dashboard.stripe.com/coupons">coupon management</a> page
        of the Stripe dashboard. However, deleting a coupon does not affect any
        customers who have already applied the coupon; it means that new
        customers can’t redeem the coupon. You can also delete coupons via the
        API.</p>
      tags:
        - Coupons
      summary: Delete Coupons Coupon
    get:
      description: <p>Retrieves the coupon with the given ID.</p>
      tags:
        - Coupons
      summary: Retrieve Coupons Coupon
    post:
      description: >-
        <p>Updates the metadata of a coupon. Other coupon details (currency,
        duration, amount_off) are, by design, not edi
      tags:
        - Coupons
      summary: Create Coupons Coupon
