openapi: 3.0.0
info:
  title: Stripe Disputes API
paths:
  /v1/disputes:
    get:
      description: <p>Returns a list of your disputes.</p>
      tags:
        - Disputes
      summary: Retrieve Disputes
  /v1/disputes/{dispute}:
    get:
      description: <p>Retrieves the dispute with the given ID.</p>
      tags:
        - Disputes
      summary: Retrieve Disputes Dispute
    post:
      description: >-
        <p>When you get a dispute, contacting your customer is always the best
        first step. If that doesn’t work, you can submit evidence to help us
        resolve the dispute in your favor. You can do this in your <a
        href="https://dashboard.stripe.com/disputes">dashboard</a>, but if you
        prefer, you can use the API to submit evidence programmatically.</p>


        <p>Depending on your dispute type, different evidence fields will give
        you a better chance of winning your dispute. To figure out which
        evidence fields to provide, see our <a
        href="/docs/disputes/categories">guide to dispute types</a>.</p>
      tags:
        - Disputes
      summary: Create Disputes Dispute
  /v1/disputes/{dispute}/close:
    post:
      description: >-
        <p>Closing the dispute for a charge indicates that you do not have any
        evidence to submit and are essentially dismissing the dispute,
        acknowledging it as lost.</p>


        <p>The status of the dispute will change from
        <code>needs_response</code> to <code>lost</code>. <em>Closing a dispute
        is irreversible
      tags:
        - Close
        - Disputes
      summary: Create Disputes Dispute Close
