openapi: 3.0.0
info:
  title: Stripe Link API
paths:
  /v1/link_account_sessions:
    post:
      description: >-
        <p>To launch the Financial Connections authorization flow, create a
        <code>Session</code>. The session’s <code>client_secret</code> can be
        used to launch the flow using Stripe.js.</p>
      tags:
        - Accounts
        - Link
        - Sessions
      summary: Create Link Account Sessions
  /v1/link_account_sessions/{session}:
    get:
      description: >-
        <p>Retrieves the details of a Financial Connections
        <code>Session</code></p>
      tags:
        - Accounts
        - Link
        - Sessions
      summary: Retrieve Link Account Sessions Session
  /v1/linked_accounts:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Account</code>
        objects.</p>
      tags:
        - Accounts
        - Linked
      summary: Retrieve Linked Accounts
  /v1/linked_accounts/{account}:
    get:
      description: >-
        <p>Retrieves the details of an Financial Connections
        <code>Account</code>.</p>
      tags:
        - Accounts
        - Linked
      summary: Retrieve Linked Accounts Account
  /v1/linked_accounts/{account}/disconnect:
    post:
      description: >-
        <p>Disables your access to a Financial Connections <code>Account</code>.
        You will no longer be able to access data associated with the account
        (e.g. balances, transactions).</p>
      tags:
        - Accounts
        - Disconnect
        - Linked
      summary: Create Linked Accounts Account Disconnect
  /v1/linked_accounts/{account}/owners:
    get:
      description: <p>Lists all owners for a given <code>Account</code></p>
      tags:
        - Accounts
        - Linked
        - Owners
      summary: Retrieve Linked Accounts Account Owners
  /v1/linked_accounts/{account}/refresh:
    post:
      description: >-
        <p>Refreshes the data associated with a Financial Connections
        <code>Account</
      tags:
        - Accounts
        - Linked
        - Refresh
      summary: Create Linked Accounts Account Refresh
