openapi: 3.0.0
info:
  title: Stripe Payment Links API
paths:
  /v1/payment_links:
    get:
      description: <p>Returns a list of your payment links.</p>
      tags:
        - Links
        - Payments
      summary: Retrieve Payment Links
    post:
      description: <p>Creates a payment link.</p>
      tags:
        - Links
        - Payments
      summary: Create Payment Links
  /v1/payment_links/{payment_link}:
    get:
      description: <p>Retrieve a payment link.</p>
      tags:
        - Link
        - Links
        - Payments
      summary: Retrieve Payment Links Payment Link
    post:
      description: <p>Updates a payment link.</p>
      tags:
        - Link
        - Links
        - Payments
      summary: Create Payment Links Payment Link
  /v1/payment_links/{payment_link}/line_items:
    get:
      description: >-
        <p>When retrieving a payment link, there is an includable
        <strong>line_items</strong> property containing the first handful of
        those items. There is also a URL where you can retrieve the full
        (paginated) list of line 
      tags:
        - Items
        - Line
        - Link
        - Links
        - Payments
      summary: Retrieve Payment Links Payment Link Line Items
