openapi: 3.0.0
info:
  title: Stripe Reporting API
paths:
  /v1/reporting/report_runs:
    get:
      description: >-
        <p>Returns a list of Report Runs, with the most recent appearing
        first.</p>
      tags:
        - Reporting
        - Reports
        - Runs
      summary: Retrieve Reporting Report Runs
    post:
      description: >-
        <p>Creates a new object and begin running the report. (Certain report
        types require a <a
        href="https://stripe.com/docs/keys#test-live-modes">live-mode API
        key</a>.)</p>
      tags:
        - Reporting
        - Reports
        - Runs
      summary: Create Reporting Report Runs
  /v1/reporting/report_runs/{report_run}:
    get:
      description: <p>Retrieves the details of an existing Report Run.</p>
      tags:
        - Reporting
        - Reports
        - Runs
      summary: Retrieve Reporting Report Runs Report Run
  /v1/reporting/report_types:
    get:
      description: <p>Returns a full list of Report Types.</p>
      tags:
        - Reporting
        - Reports
        - Types
      summary: Retrieve Reporting Report Types
  /v1/reporting/report_types/{report_type}:
    get:
      description: >-
        <p>Retrieves the details of a Report Type. (Certain report types require
        a <a href="https://stripe.com/docs/keys#test-live-modes">live-mode API
        key
      tags:
        - Reporting
        - Reports
        - Types
      summary: Retrieve Reporting Report Types Report Type
