openapi: 3.0.0
info:
  title: Stripe Shipping Rates API
paths:
  /v1/shipping_rates:
    get:
      description: <p>Returns a list of your shipping rates.</p>
      tags:
        - Rates
        - Shipping
      summary: Retrieve Shipping Rates
    post:
      description: <p>Creates a new shipping rate object.</p>
      tags:
        - Rates
        - Shipping
      summary: Create Shipping Rates
  /v1/shipping_rates/{shipping_rate_token}:
    get:
      description: <p>Returns the shipping rate object with the given ID.</p>
      tags:
        - Rates
        - Shipping
        - Tokens
      summary: Retrieve Shipping Rates Shipping Rate Token
    post:
      description: <p>Updates an existing shipping rate o
      tags:
        - Rates
        - Shipping
        - Tokens
      summary: Create Shipping Rates Shipping Rate Token
