openapi: 3.0.0
info:
  title: Stripe Sigma API
paths:
  /v1/sigma/scheduled_query_runs:
    get:
      description: <p>Returns a list of scheduled query runs.</p>
      tags:
        - Queries
        - Runs
        - Scheduled
      summary: Retrieve Sigma Scheduled Query Runs
  /v1/sigma/scheduled_query_runs/{scheduled_query_run}:
    get:
      description: <p>Retrieves the details of an scheduled que
      tags:
        - Queries
        - Runs
        - Scheduled
      summary: Retrieve Sigma Scheduled Query Runs Scheduled Query Run
