openapi: 3.0.0
info:
  title: Stripe Sources API
paths:
  /v1/sources:
    post:
      description: <p>Creates a new source object.</p>
      tags:
        - Sources
      summary: Create Sources
  /v1/sources/{source}:
    get:
      description: >-
        <p>Retrieves an existing source object. Supply the unique source ID from
        a source creation request and Stripe will return the corresponding
        up-to-date source object information.</p>
      tags:
        - Sources
      summary: Retrieve Sources Source
    post:
      description: >-
        <p>Updates the specified source by setting the values of the parameters
        passed. Any parameters not provided will be left unchanged.</p>


        <p>This request accepts the <code>metadata</code> and <code>owner</code>
        as arguments. It is also possible to update type specific information
        for selected payment methods. Please refer to our <a
        href="/docs/sources">payment method guides</a> for more detail.</p>
      tags:
        - Sources
      summary: Create Sources Source
  /v1/sources/{source}/mandate_notifications/{mandate_notification}:
    get:
      description: <p>Retrieves a new Source MandateNotification.</p>
      tags:
        - Mandate
        - Notifications
        - Sources
      summary: Retrieve Sources Source Mandate Notifications Mandate Notification
  /v1/sources/{source}/source_transactions:
    get:
      description: <p>List source transactions for a given source.</p>
      tags:
        - Sources
        - Transactions
      summary: Retrieve Sources Source Source Transactions
  /v1/sources/{source}/source_transactions/{source_transaction}:
    get:
      description: >-
        <p>Retrieve an existing source transaction object. Supply the unique
        source ID from a source creation request and the source transaction ID
        and Stripe will return the corresponding up-to-date source object
        information.</p>
      tags:
        - Sources
        - Transactions
      summary: Retrieve Sources Source Source Transactions Source Transaction
  /v1/sources/{source}/verify:
    post:
      description: <p>Verify a given s
      tags:
        - Sources
        - Verify
      summary: Create Sources Source Verify
