openapi: 3.0.0
info:
  title: Stripe Transfers API
paths:
  /v1/transfers:
    get:
      description: >-
        <p>Returns a list of existing transfers sent to connected accounts. The
        transfers are returned in sorted order, with the most recently created
        transfers appearing first.</p>
      tags:
        - Transfers
      summary: Retrieve Transfers
    post:
      description: >-
        <p>To send funds from your Stripe account to a connected account, you
        create a new transfer object. Your <a href="#balance">Stripe balance</a>
        must be able to cover the transfer amount, or you’ll receive an
        “Insufficient Funds” error.</p>
      tags:
        - Transfers
      summary: Create Transfers
  /v1/transfers/{id}/reversals:
    get:
      description: >-
        <p>You can see a list of the reversals belonging to a specific transfer.
        Note that the 10 most recent reversals are always available by default
        on the transfer object. If you need more than those 10, you can use this
        API method and the <code>limit</code> and <code>starting_after</code>
        parameters to page through additional reversals.</p>
      tags:
        - Reversals
        - Transfers
      summary: Retrieve Transfers Id Reversals
    post:
      description: >-
        <p>When you create a new reversal, you must specify a transfer to create
        it on.</p>


        <p>When reversing transfers, you can optionally reverse part of the
        transfer. You can do so as many times as you wish until the entire
        transfer has been reversed.</p>


        <p>Once entirely reversed, a transfer can’t be reversed again. This
        method will return an error when called on an already-reversed transfer,
        or when trying to reverse more money than is left on a transfer.</p>
      tags:
        - Reversals
        - Transfers
      summary: Create Transfers Id Reversals
  /v1/transfers/{transfer}:
    get:
      description: >-
        <p>Retrieves the details of an existing transfer. Supply the unique
        transfer ID from either a transfer creation request or the transfer
        list, and Stripe will return the corresponding transfer information.</p>
      tags:
        - Transfers
      summary: Retrieve Transfers Transfer
    post:
      description: >-
        <p>Updates the specified transfer by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>


        <p>This request accepts only metadata as an argument.</p>
      tags:
        - Transfers
      summary: Create Transfers Transfer
  /v1/transfers/{transfer}/reversals/{id}:
    get:
      description: >-
        <p>By default, you can see the 10 most recent reversals stored directly
        on the transfer object, but you can also retrieve details about a
        specific reversal stored on the transfer.</p>
      tags:
        - Reversals
        - Transfers
      summary: Retrieve Transfers Transfer Reversals Id
    post:
      description: >-
        <p>Updates the specified reversal by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>


        <p>This request only accepts metadata and description as argu
      tags:
        - Reversals
        - Transfers
      summary: Create Transfers Transfer Reversals Id
