tracks:
- id: 5d8b1553-a448-489e-84f3-86042de0e433
  segmentStyle:
    strokeColor: "#000000"
    strokeWidth: 12
    selectionColor: "#006400"
    fullySelected: false
  stationStyle:
    strokeColor: "#000000"
    strokeWidth: 4
    fillColor: white
    stationRadius: 10
    selectionColor: "#006400"
    fullySelected: false
  segments:
  - stationA:
      position:
        x: 136
        y: 88
      id: 55e3e4c3
      name: Retrieve Application Fees
      offsetFactor:
    stationB:
      position:
        x: 136
        y: 224
      id: f44ed7f0
      name: Retrieve Application Fees Refund
      offsetFactor:
    stationsUser:
    - position:
        x: 136
        y: 88
      id: 55e3e4c3
      name: Retrieve Application Fees
      offsetFactor:
    - position:
        x: 136
        y: 224
      id: f44ed7f0
      name: Retrieve Application Fees Refund
      offsetFactor:
    stationsAuto: []
    id: 2e075398-967f-4ba8-b93b-ab0372f6826c
  - stationA:
      position:
        x: 136
        y: 224
      id: f44ed7f0
      name: Retrieve Application Fees Refund
      offsetFactor:
    stationB:
      position:
        x: 315
        y: 305
      id: 20b12595
      name: Update Application Fees Refund
      offsetFactor:
    stationsUser:
    - position:
        x: 136
        y: 224
      id: f44ed7f0
      name: Retrieve Application Fees Refund
      offsetFactor:
    - position:
        x: 315
        y: 305
      id: 20b12595
      name: Update Application Fees Refund
      offsetFactor:
    stationsAuto: []
    id: bd7f6497-555d-42b8-aa17-8317a1fec229
  - stationA:
      position:
        x: 315
        y: 305
      id: 20b12595
      name: Update Application Fees Refund
      offsetFactor:
    stationB:
      position:
        x: 659
        y: 305
      id: 85bb8087
      name: Retrieve Application Fee
      offsetFactor:
    stationsUser:
    - position:
        x: 315
        y: 305
      id: 20b12595
      name: Update Application Fees Refund
      offsetFactor:
    - position:
        x: 659
        y: 305
      id: 85bb8087
      name: Retrieve Application Fee
      offsetFactor:
    stationsAuto: []
    id: a3dc6e6f-9fa6-45a6-b408-6b64d46d2d5e
  - stationA:
      position:
        x: 659
        y: 305
      id: 85bb8087
      name: Retrieve Application Fee
      offsetFactor:
    stationB:
      position:
        x: 659
        y: 181
      id: 31c4fe06
      name: Create Application Fee Refund
      offsetFactor:
    stationsUser:
    - position:
        x: 659
        y: 305
      id: 85bb8087
      name: Retrieve Application Fee
      offsetFactor:
    - position:
        x: 659
        y: 181
      id: 31c4fe06
      name: Create Application Fee Refund
      offsetFactor:
    stationsAuto: []
    id: f0c972be-d506-498a-b52c-cdcb9c35164d
  - stationA:
      position:
        x: 659
        y: 181
      id: 31c4fe06
      name: Create Application Fee Refund
      offsetFactor:
    stationB:
      position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    stationsUser:
    - position:
        x: 659
        y: 181
      id: 31c4fe06
      name: Create Application Fee Refund
      offsetFactor:
    - position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    stationsAuto: []
    id: aecab254-c117-4ce3-a1fc-46311f421de4
  - stationA:
      position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    stationB:
      position:
        x: 547
        y: 90
      id: 73fe99b1
      name: Refund Application Fee
      offsetFactor:
    stationsUser:
    - position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    - position:
        x: 547
        y: 90
      id: 73fe99b1
      name: Refund Application Fee
      offsetFactor:
    stationsAuto: []
    id: a2f3c6b3-afd9-4a2e-a394-45605de1b574
  - stationA:
      position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    stationB:
      position:
        x: 547
        y: 90
      id: 73fe99b1
      name: Refund Application Fee
      offsetFactor:
    stationsUser:
    - position:
        x: 441
        y: 181
      id: 6a98f474
      name: Retrieve Application Fee Refunds
      offsetFactor:
    - position:
        x: 547
        y: 90
      id: 73fe99b1
      name: Refund Application Fee
      offsetFactor:
    stationsAuto: []
    id: 7c37b6fc-fb0d-4b8f-b39e-885caed6a7e5
  stationsMinor: []
connections: []