openapi: 3.0.0
info:
  title: Stripe Apple Pay API
paths:
  /v1/apple_pay/domains:
    get:
      description: <p>List apple pay domains.</p>
      tags:
        - Apple
        - Domains
        - Pay
      summary: Retrieve Apple Pay Domains
    post:
      description: <p>Create an apple pay domain.</p>
      tags:
        - Apple
        - Domains
        - Pay
      summary: Create Apple Pay Domains
  /v1/apple_pay/domains/{domain}:
    delete:
      description: <p>Delete an apple pay domain.</p>
      tags:
        - Apple
        - Domains
        - Pay
      summary: Delete Apple Pay Domains Domain
    get:
      description: <p>Retrieve an apple pay d
      tags:
        - Apple
        - Domains
        - Pay
      summary: Retrieve Apple Pay Domains Domain
