tracks:
- id: 1fefaea6-8b44-497e-9bd6-d089d1c63e7b
  segmentStyle:
    strokeColor: "#000000"
    strokeWidth: 12
    selectionColor: "#006400"
    fullySelected: false
  stationStyle:
    strokeColor: "#000000"
    strokeWidth: 4
    fillColor: white
    stationRadius: 10
    selectionColor: "#006400"
    fullySelected: false
  segments:
  - stationA:
      position:
        x: 191
        y: 120
      id: 8b190341
      name: Retrieve Application Secrets
      offsetFactor:
    stationB:
      position:
        x: 514
        y: 248
      id: 5452b3e6
      name: Create Application Secret
      offsetFactor:
    stationsUser:
    - position:
        x: 191
        y: 120
      id: 8b190341
      name: Retrieve Application Secrets
      offsetFactor:
    - position:
        x: 514
        y: 248
      id: 5452b3e6
      name: Create Application Secret
      offsetFactor:
    stationsAuto: []
    id: 14715baf-c48f-4fb3-86a7-77c10a7231cc
  - stationA:
      position:
        x: 514
        y: 248
      id: 5452b3e6
      name: Create Application Secret
      offsetFactor:
    stationB:
      position:
        x: 514
        y: 165
      id: fb7aaa03
      name: Delete Application Secret
      offsetFactor:
    stationsUser:
    - position:
        x: 514
        y: 248
      id: 5452b3e6
      name: Create Application Secret
      offsetFactor:
    - position:
        x: 514
        y: 165
      id: fb7aaa03
      name: Delete Application Secret
      offsetFactor:
    stationsAuto: []
    id: 6f842de5-2419-4828-a3f0-9b625d8c6992
  - stationA:
      position:
        x: 514
        y: 165
      id: fb7aaa03
      name: Delete Application Secret
      offsetFactor:
    stationB:
      position:
        x: 643
        y: 85
      id: dd58f833
      name: Retrieve Application Secret
      offsetFactor:
    stationsUser:
    - position:
        x: 514
        y: 165
      id: fb7aaa03
      name: Delete Application Secret
      offsetFactor:
    - position:
        x: 643
        y: 85
      id: dd58f833
      name: Retrieve Application Secret
      offsetFactor:
    stationsAuto: []
    id: c77124c4-58a7-42aa-9230-aaf0cd34ecbf
  stationsMinor: []
connections: []