openapi: 3.0.0
info:
  title: Stripe Financial Connections API
paths:
  /v1/financial_connections/accounts:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Account</code>
        objects.</p>
      tags:
        - Accounts
        - Connections
        - Financial
      summary: Retrieve Financial Connections Accounts
  /v1/financial_connections/accounts/{account}:
    get:
      description: >-
        <p>Retrieves the details of an Financial Connections
        <code>Account</code>.</p>
      tags:
        - Accounts
        - Connections
        - Financial
      summary: Retrieve Financial Connections Accounts Account
  /v1/financial_connections/accounts/{account}/disconnect:
    post:
      description: >-
        <p>Disables your access to a Financial Connections <code>Account</code>.
        You will no longer be able to access data associated with the account
        (e.g. balances, transactions).</p>
      tags:
        - Accounts
        - Connections
        - Disconnect
        - Financial
      summary: Create Financial Connections Accounts Account Disconnect
  /v1/financial_connections/accounts/{account}/owners:
    get:
      description: <p>Lists all owners for a given <code>Account</code></p>
      tags:
        - Accounts
        - Connections
        - Financial
        - Owners
      summary: Retrieve Financial Connections Accounts Account Owners
  /v1/financial_connections/accounts/{account}/refresh:
    post:
      description: >-
        <p>Refreshes the data associated with a Financial Connections
        <code>Account</code>.</p>
      tags:
        - Accounts
        - Connections
        - Financial
        - Refresh
      summary: Create Financial Connections Accounts Account Refresh
  /v1/financial_connections/accounts/{account}/subscribe:
    post:
      description: >-
        <p>Subscribes to periodic refreshes of data associated with a Financial
        Connections <code>Account</code>.</p>
      tags:
        - Accounts
        - Connections
        - Financial
        - Subscribe
      summary: Create Financial Connections Accounts Account Subscribe
  /v1/financial_connections/accounts/{account}/unsubscribe:
    post:
      description: >-
        <p>Unsubscribes from periodic refreshes of data associated with a
        Financial Connections <code>Account</code>.</p>
      tags:
        - Accounts
        - Connections
        - Financial
        - Unsubscribe
      summary: Create Financial Connections Accounts Account Unsubscribe
  /v1/financial_connections/sessions:
    post:
      description: >-
        <p>To launch the Financial Connections authorization flow, create a
        <code>Session</code>. The session’s <code>client_secret</code> can be
        used to launch the flow using Stripe.js.</p>
      tags:
        - Connections
        - Financial
        - Sessions
      summary: Create Financial Connections Sessions
  /v1/financial_connections/sessions/{session}:
    get:
      description: >-
        <p>Retrieves the details of a Financial Connections
        <code>Session</code></p>
      tags:
        - Connections
        - Financial
        - Sessions
      summary: Retrieve Financial Connections Sessions Session
  /v1/financial_connections/transactions:
    get:
      description: >-
        <p>Returns a list of Financial Connections <code>Transaction</code>
        objects.</p>
      tags:
        - Connections
        - Financial
        - Transactions
      summary: Retrieve Financial Connections Transactions
  /v1/financial_connections/transactions/{transaction}:
    get:
      description: <p>Retrieves the details of a Financial Connections <code>Transaction<
      tags:
        - Connections
        - Financial
        - Transactions
      summary: Retrieve Financial Connections Transactions Transaction
