tracks:
- id: b147fe5b-afc6-40c4-a93e-cd5fa3a4b8eb
  segmentStyle:
    strokeColor: "#000000"
    strokeWidth: 12
    selectionColor: "#006400"
    fullySelected: false
  stationStyle:
    strokeColor: "#000000"
    strokeWidth: 6
    fillColor: white
    stationRadius: 12
    selectionColor: "#006400"
    fullySelected: false
  segments:
  - stationA:
      position:
        x: 292
        y: 443
      id: 0d880209
      name: Retrieve Products
      offsetFactor:
    stationB:
      position:
        x: 163
        y: 180
      id: bbc7b5ad
      name: Create Product
      offsetFactor:
    stationsUser:
    - position:
        x: 292
        y: 443
      id: 0d880209
      name: Retrieve Products
      offsetFactor:
    - position:
        x: 163
        y: 180
      id: bbc7b5ad
      name: Create Product
      offsetFactor:
    stationsAuto: []
    id: c3ae9f7f-b29c-48b5-ac0d-eb44387c945f
  - stationA:
      position:
        x: 163
        y: 180
      id: bbc7b5ad
      name: Create Product
      offsetFactor:
    stationB:
      position:
        x: 521
        y: 299
      id: 4cda8191
      name: Search Products
      offsetFactor:
    stationsUser:
    - position:
        x: 163
        y: 180
      id: bbc7b5ad
      name: Create Product
      offsetFactor:
    - position:
        x: 521
        y: 299
      id: 4cda8191
      name: Search Products
      offsetFactor:
    stationsAuto: []
    id: 79319587-e76c-4ba7-afe2-895e3f226a2c
  - stationA:
      position:
        x: 521
        y: 299
      id: 4cda8191
      name: Search Products
      offsetFactor:
    stationB:
      position:
        x: 521
        y: 78
      id: d67d7952
      name: Delete Product
      offsetFactor:
    stationsUser:
    - position:
        x: 521
        y: 299
      id: 4cda8191
      name: Search Products
      offsetFactor:
    - position:
        x: 521
        y: 78
      id: d67d7952
      name: Delete Product
      offsetFactor:
    stationsAuto: []
    id: ea15aeaf-8e52-47f7-8443-92e5f375353b
  - stationA:
      position:
        x: 521
        y: 78
      id: d67d7952
      name: Delete Product
      offsetFactor:
    stationB:
      position:
        x: 671
        y: 192
      id: 2b171153
      name: Retrieve Product
      offsetFactor:
    stationsUser:
    - position:
        x: 521
        y: 78
      id: d67d7952
      name: Delete Product
      offsetFactor:
    - position:
        x: 671
        y: 192
      id: 2b171153
      name: Retrieve Product
      offsetFactor:
    stationsAuto: []
    id: 8f070fd1-2d14-4f8e-897e-49d0cfa4cc0e
  - stationA:
      position:
        x: 671
        y: 192
      id: 2b171153
      name: Retrieve Product
      offsetFactor:
    stationB:
      position:
        x: 897
        y: 316
      id: 6e064e6a
      name: Update Product
      offsetFactor:
    stationsUser:
    - position:
        x: 671
        y: 192
      id: 2b171153
      name: Retrieve Product
      offsetFactor:
    - position:
        x: 897
        y: 316
      id: 6e064e6a
      name: Update Product
      offsetFactor:
    stationsAuto: []
    id: 438baea6-a621-4ac5-8120-21ac4bbf0fac
  stationsMinor: []
connections: []