openapi: 3.0.0
info:
  title: Stripe Products API
paths:
  /v1/products:
    get:
      description: >-
        <p>Returns a list of your products. The products are returned sorted by
        creation date, with the most recently created products appearing
        first.</p>
      tags:
        - Products
      summary: Retrieve Products
    post:
      description: <p>Creates a new product object.</p>
      tags:
        - Products
      summary: Create Products
  /v1/products/search:
    get:
      description: >-
        <p>Search for products you’ve previously created using Stripe’s <a
        href="/docs/search#search-query-language">Search Query Language</a>.

        Don’t use search in read-after-write flows where strict consistency is
        necessary. Under normal operating

        conditions, data is searchable in less than a minute. Occasionally,
        propagation of new or updated data can be up

        to an hour behind during outages. Search functionality is not available
        to merchants in India.</p>
      tags:
        - Products
        - Search
      summary: Retrieve Products Search
  /v1/products/{id}:
    delete:
      description: >-
        <p>Delete a product. Deleting a product is only possible if it has no
        prices associated with it. Additionally, deleting a product with
        <code>type=good</code> is only possible if it has no SKUs associated
        with it.</p>
      tags:
        - Products
      summary: Delete Products Id
    get:
      description: >-
        <p>Retrieves the details of an existing product. Supply the unique
        product ID from either a product creation request or the product list,
        and Stripe will return the corresponding product information.</p>
      tags:
        - Products
      summary: Retrieve Products Id
    post:
      description: >-
        <p>Updates the specific product by setting the values of the parameters
        passed. Any parameters not provided will be left unch
      tags:
        - Products
      summary: Create Products Id
