openapi: 3.0.0
info:
  title: Stripe Promotion Codes API
paths:
  /v1/promotion_codes:
    get:
      description: <p>Returns a list of your promotion codes.</p>
      tags:
        - Codes
        - Promotion
      summary: Retrieve Promotion Codes
    post:
      description: >-
        <p>A promotion code points to a coupon. You can optionally restrict the
        code to a specific customer, redemption limit, and expiration date.</p>
      tags:
        - Codes
        - Promotion
      summary: Create Promotion Codes
  /v1/promotion_codes/{promotion_code}:
    get:
      description: >-
        <p>Retrieves the promotion code with the given ID. In order to retrieve
        a promotion code by the customer-facing <code>code</code> use <a
        href="/docs/api/promotion_codes/list">list</a> with the desired
        <code>code</code>.</p>
      tags:
        - Code
        - Codes
        - Promotion
      summary: Retrieve Promotion Codes Promotion Code
    post:
      description: >-
        <p>Updates the specified promotion code by setting the values of the
        parameters passed. Most fields are, by design, not edi
      tags:
        - Code
        - Codes
        - Promotion
      summary: Create Promotion Codes Promotion Code
