openapi: 3.0.0
info:
  title: Stripe Radar API
paths:
  /v1/radar/early_fraud_warnings:
    get:
      description: <p>Returns a list of early fraud warnings.</p>
      tags:
        - Early
        - Fraud
        - Radar
        - Warnings
      summary: Retrieve Radar Early Fraud Warnings
  /v1/radar/early_fraud_warnings/{early_fraud_warning}:
    get:
      description: >-
        <p>Retrieves the details of an early fraud warning that has previously
        been created. </p>


        <p>Please refer to the <a href="#early_fraud_warning_object">early fraud
        warning</a> object reference for more details.</p>
      tags:
        - Early
        - Fraud
        - Radar
        - Warning
        - Warnings
      summary: Retrieve Radar Early Fraud Warnings Early Fraud Warning
  /v1/radar/value_list_items:
    get:
      description: >-
        <p>Returns a list of <code>ValueListItem</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - Items
        - Radar
        - Value
      summary: Retrieve Radar Value List Items
    post:
      description: >-
        <p>Creates a new <code>ValueListItem</code> object, which is added to
        the specified parent value list.</p>
      tags:
        - Items
        - Radar
        - Value
      summary: Create Radar Value List Items
  /v1/radar/value_list_items/{item}:
    delete:
      description: >-
        <p>Deletes a <code>ValueListItem</code> object, removing it from its
        parent value list.</p>
      tags:
        - Items
        - Radar
        - Value
      summary: Delete Radar Value List Items Item
    get:
      description: <p>Retrieves a <code>ValueListItem</code> object.</p>
      tags:
        - Items
        - Radar
        - Value
      summary: Retrieve Radar Value List Items Item
  /v1/radar/value_lists:
    get:
      description: >-
        <p>Returns a list of <code>ValueList</code> objects. The objects are
        sorted in descending order by creation date, with the most recently
        created object appearing first.</p>
      tags:
        - Radar
        - Value
      summary: Retrieve Radar Value Lists
    post:
      description: >-
        <p>Creates a new <code>ValueList</code> object, which can then be
        referenced in rules.</p>
      tags:
        - Radar
        - Value
      summary: Create Radar Value Lists
  /v1/radar/value_lists/{value_list}:
    delete:
      description: >-
        <p>Deletes a <code>ValueList</code> object, also deleting any items
        contained within the value list. To be deleted, a value list must not be
        referenced in any rules.</p>
      tags:
        - Radar
        - Value
      summary: Delete Radar Value Lists Value List
    get:
      description: <p>Retrieves a <code>ValueList</code> object.</p>
      tags:
        - Radar
        - Value
      summary: Retrieve Radar Value Lists Value List
    post:
      description: >-
        <p>Updates a <code>ValueList</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left unchanged.
        Note that <code>item_type</code> is immu
      tags:
        - Radar
        - Value
      summary: Create Radar Value Lists Value List
