openapi: 3.0.0
info:
  title: Stripe Terminal API
paths:
  /v1/terminal/configurations:
    get:
      description: <p>Returns a list of <code>Configuration</code> objects.</p>
      tags:
        - Configurations
        - Terminal
      summary: Retrieve Terminal Configurations
    post:
      description: <p>Creates a new <code>Configuration</code> object.</p>
      tags:
        - Configurations
        - Terminal
      summary: Create Terminal Configurations
  /v1/terminal/configurations/{configuration}:
    delete:
      description: <p>Deletes a <code>Configuration</code> object.</p>
      tags:
        - Configurations
        - Terminal
      summary: Delete Terminal Configurations Configuration
    get:
      description: <p>Retrieves a <code>Configuration</code> object.</p>
      tags:
        - Configurations
        - Terminal
      summary: Retrieve Terminal Configurations Configuration
    post:
      description: <p>Updates a new <code>Configuration</code> object.</p>
      tags:
        - Configurations
        - Terminal
      summary: Create Terminal Configurations Configuration
  /v1/terminal/connection_tokens:
    post:
      description: >-
        <p>To connect to a reader the Stripe Terminal SDK needs to retrieve a
        short-lived connection token from Stripe, proxied through your server.
        On your backend, add an endpoint that creates and returns a connection
        token.</p>
      tags:
        - Connections
        - Terminal
        - Tokens
      summary: Create Terminal Connection Tokens
  /v1/terminal/locations:
    get:
      description: <p>Returns a list of <code>Location</code> objects.</p>
      tags:
        - Locations
        - Terminal
      summary: Retrieve Terminal Locations
    post:
      description: >-
        <p>Creates a new <code>Location</code> object.

        For further details, including which address fields are required in each
        country, see the <a href="/docs/terminal/fleet/locations">Manage
        locations</a> guide.</p>
      tags:
        - Locations
        - Terminal
      summary: Create Terminal Locations
  /v1/terminal/locations/{location}:
    delete:
      description: <p>Deletes a <code>Location</code> object.</p>
      tags:
        - Locations
        - Terminal
      summary: Delete Terminal Locations Location
    get:
      description: <p>Retrieves a <code>Location</code> object.</p>
      tags:
        - Locations
        - Terminal
      summary: Retrieve Terminal Locations Location
    post:
      description: >-
        <p>Updates a <code>Location</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>
      tags:
        - Locations
        - Terminal
      summary: Create Terminal Locations Location
  /v1/terminal/readers:
    get:
      description: <p>Returns a list of <code>Reader</code> objects.</p>
      tags:
        - Readers
        - Terminal
      summary: Retrieve Terminal Readers
    post:
      description: <p>Creates a new <code>Reader</code> object.</p>
      tags:
        - Readers
        - Terminal
      summary: Create Terminal Readers
  /v1/terminal/readers/{reader}:
    delete:
      description: <p>Deletes a <code>Reader</code> object.</p>
      tags:
        - Readers
        - Terminal
      summary: Delete Terminal Readers Reader
    get:
      description: <p>Retrieves a <code>Reader</code> object.</p>
      tags:
        - Readers
        - Terminal
      summary: Retrieve Terminal Readers Reader
    post:
      description: >-
        <p>Updates a <code>Reader</code> object by setting the values of the
        parameters passed. Any parameters not provided will be left
        unchanged.</p>
      tags:
        - Readers
        - Terminal
      summary: Create Terminal Readers Reader
  /v1/terminal/readers/{reader}/cancel_action:
    post:
      description: <p>Cancels the current reader action.</p>
      tags:
        - Actions
        - Cancel
        - Readers
        - Terminal
      summary: Create Terminal Readers Reader Cancel Action
  /v1/terminal/readers/{reader}/process_payment_intent:
    post:
      description: <p>Initiates a payment flow on a Reader.</p>
      tags:
        - Intent
        - Payments
        - Process
        - Readers
        - Terminal
      summary: Create Terminal Readers Reader Process Payment Intent
  /v1/terminal/readers/{reader}/process_setup_intent:
    post:
      description: <p>Initiates a setup intent flow on a Reader.</p>
      tags:
        - Intent
        - Process
        - Readers
        - Setup
        - Terminal
      summary: Create Terminal Readers Reader Process Setup Intent
  /v1/terminal/readers/{reader}/refund_payment:
    post:
      description: <p>Initiates a refund on a Reader</p>
      tags:
        - Payments
        - Readers
        - Refunds
        - Terminal
      summary: Create Terminal Readers Reader Refund Payment
  /v1/terminal/readers/{reader}/set_reader_display:
    post:
      description: <p>Sets reader display to show cart de
      tags:
        - Display
        - Readers
        - Sets
        - Terminal
      summary: Create Terminal Readers Reader Set Reader Display
