openapi: 3.0.0
info:
  title: Stripe Tokens API
paths:
  /v1/tokens:
    post:
      description: >-
        <p>Creates a single-use token that represents a bank account’s details.

        You can use this token with any API method in place of a bank account
        dictionary. You can only use this token once. To do so, attach it to a
        <a href="#accounts">Custom account</a>.</p>
      tags:
        - Tokens
      summary: Create Tokens
  /v1/tokens/{token}:
    get:
      description: <p>Retrieves the token with the giv
      tags:
        - Tokens
      summary: Retrieve Tokens Token
