openapi: 3.0.0
info:
  title: Stripe Topups API
paths:
  /v1/topups:
    get:
      description: <p>Returns a list of top-ups.</p>
      tags:
        - Topups
      summary: Retrieve Topups
    post:
      description: <p>Top up the balance of an account</p>
      tags:
        - Topups
      summary: Create Topups
  /v1/topups/{topup}:
    get:
      description: >-
        <p>Retrieves the details of a top-up that has previously been created.
        Supply the unique top-up ID that was returned from your previous
        request, and Stripe will return the corresponding top-up
        information.</p>
      tags:
        - Topups
      summary: Retrieve Topups Topup
    post:
      description: >-
        <p>Updates the metadata of a top-up. Other top-up details are not
        editable by design.</p>
      tags:
        - Topups
      summary: Create Topups Topup
  /v1/topups/{topup}/cancel:
    post:
      description: <p>Cancels a top-up. Only pending top-ups can be can
      tags:
        - Cancel
        - Topups
      summary: Create Topups Topup Cancel
