openapi: 3.1.0
info:
  x-publicVersion: true
  title: Authentication Webhooks
tags:
  - name: General
webhooks:
  balancePlatform.authentication.created:
    post:
      tags:
        - General
      summary: Cardholder authenticated
      description: >-
        Adyen sends this webhook when the process of cardholder authentication
        is finalized, whether it is completed successfully, fails, or expires.
      x-addedInVersion: '1'
      operationId: post-balancePlatform.authentication.created
      x-sortIndex: 1
      x-methodName: cardholderAuthenticated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              balancePlatform-authentication-created-authenticated-challenge:
                $ref: >-
                  #/components/examples/post-balancePlatform.authentication.created-balancePlatform-authentication-created-authenticated-challenge
              balancePlatform-authentication-created-authenticated-frictionless:
                $ref: >-
                  #/components/examples/post-balancePlatform.authentication.created-balancePlatform-authentication-created-authenticated-frictionless
              balancePlatform-authentication-created-rejected:
                $ref: >-
                  #/components/examples/post-balancePlatform.authentication.created-balancePlatform-authentication-created-rejected
            schema:
              $ref: '#/components/schemas/AuthenticationNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                balancePlatform-authentication-created-authenticated-challenge:
                  $ref: '#/components/examples/WebhookAck'
                balancePlatform-authentication-created-authenticated-frictionless:
                  $ref: '#/components/examples/WebhookAck'
                balancePlatform-authentication-created-rejected:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
          description: OK - the request has succeede
