openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen BinLookup API
tags:
  - name: General
paths:
  /get3dsAvailability:
    post:
      tags:
        - Checks
        - If
        - Secure
        - Is
        - Available
        - Availability
      summary: Check if 3D Secure is available
      description: >-
        Verifies whether 3D Secure is available for the specified BIN or card
        brand. For 3D Secure 2, this endpoint also returns device fingerprinting
        keys.


        For more information, refer to [3D Secure
        2](https://docs.adyen.com/online-payments/3d-secure/native-3ds2).
  /getCostEstimate:
    post:
      tags:
        - Get
        - Fees
        - Cost
        - Estimates
        - Availability
        - Cost
        - Estimates
      summary: Get a fees cost estimate
      description: >-
        >This API is available only for merchants operating in Australia, the
        EU, and the UK.


        Use the Adyen Cost Estimation API to pre-calculate interchange and
        scheme fee costs. Knowing these costs prior actual payment authorisation
        gives you an opportunity to charge those costs to the cardholder, if
        necessary.


        To retrieve this information, make the call to the `/getCostEstimate`
        endpoint. The response to this call contains the amount of the
        interchange and scheme fees charged by the network for this transaction,
        and also which surcharging policy is possible (based on current
        regulations).


        > Since not all information is known in advance (for example, if the
        cardholder will successfully authenticate via 3D Secure or if you also
        plan to provide additional Level 2/3 data), the returned amounts are
        based on a set of assumption criteria you defi
