openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Data Protection API
tags:
  - name: General
paths:
  /requestSubjectErasure:
    post:
      tags:
        - Submit
        - Subjects
        - Erasure
        - Request.
        - Subjects
        - Erasure
      summary: Submit a Subject Erasure Request.
      description: Sends the PSP reference containing t
