weekNumber: 12
rules:
  - code: openapi-external-docs-error
    message: External Docs
  - code: openapi-info-license-error
    message: License Object
  - code: openapi-info-version-info
    message: Info Version
  - code: openapi-info-title-info
    message: Info Title
  - code: openapi-info-title-upper-case-info
    message: Info Title Upper Case
  - code: openapi-info-description-info
    message: Info Description
  - code: openapi-info-terms-of-service-info
    message: Terms of Service
  - code: openapi-info-contact-email-error
    message: Contact Email
  - code: openapi-info-contact-info
    message: Contact Object
  - code: openapi-info-contact-name-info
    message: Contact Name
  - code: openapi-info-contact-url-info
    message: Contact URL
  - code: openapi-tags-object-info
    message: Tag Object
  - code: openapi-tags-description-error
    message: Tag Descriptions
  - code: openapi-tags-name-info
    message: Tag Name
  - code: openapi-schema-description-error
    message: Schema SHOULD have a description.
  - code: openapi-schema-names-camel-case-warn
    message: Schema Name Camel Case
  - code: openapi-schema-names-snake-case-warn
    message: Schema Name Snake Case
  - code: openapi-schema-properties-format-error
    message: Schema Properties Format
  - code: openapi-schema-properties-names-pascal-case-error
    message: Schema Property Names Pascal Case
  - code: openapi-schema-properties-nullable-error
    message: Schema Properties Format
  - code: openapi-schema-properties-descriptions-error
    message: Schema Description
  - code: openapi-schema-properties-descriptions-info
    message: Schema Description
  - code: openapi-schema-properties-pii-info
    message: Schema PII
  - code: openapi-schema-properties-names-snake-case-error
    message: Schema Property Names Snake Case
  - code: openapi-schema-properties-descriptions-length-error
    message: Schema Description Length
  - code: openapi-schema-properties-type-info
    message: Schema Properties Format
  - code: openapi-schema-type-info
    message: Schema Type
  - code: openapi-schema-names-length-error
    message: Schema Name Length
  - code: openapi-schema-properties-enum-info
    message: Schema Property Enum
  - code: openapi-schema-properties-enum-casing-error
    message: Schema Property Enum Casing
  - code: openapi-schema-names-pascal-case-warn
    message: Schema Name Pascal Case
  - code: openapi-security-schemes-info
    message: Security Scheme
