openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Recurring API
tags:
  - name: General
paths:
  /createPermit:
    post:
      tags:
        - Create
        - New
        - Permits
        - Linked
        - To
        - Recurring
        - Contracts
        - Permits
      summary: Create new permits linked to a recurring contract.
      description: >-
        Create permits for a recurring contract, including support for defining
        restrictions.
  /disable:
    post:
      tags:
        - Disable
        - Stored
        - Payments
        - Details
        - Permits
        - Disable
      summary: Disable stored payment details
      description: >-
        Disables stored payment details to stop charging a shopper with this
        particular recurring detail ID.


        For more information, refer to [Disable stored
        details](https://docs.adyen.com/classic-integration/recurring-payments/disable-stored-details/).
  /disablePermit:
    post:
      tags:
        - Disable
        - null
        - Existing
        - Permits
        - Permits
        - Disable
      summary: Disable an existing permit.
      description: >-
        Disable a permit that was previously linked to a
        recurringDetailReference.
  /listRecurringDetails:
    post:
      tags:
        - Get
        - Stored
        - Payments
        - Details
        - Permits
        - Disable
        - Recurring
        - Details
      summary: Get stored payment details
      description: >-
        Lists the stored payment details for a shopper, if there are any
        available. The recurring detail ID can be used with a regular
        authorisation request to charge the shopper. A summary of the payment
        detail is returned for presentation to the shopper.


        For more information, refer to [Retrieve stored
        details](https://docs.adyen.com/classic-integration/recurring-payments/retrieve-stored-details/).
  /notifyShopper:
    post:
      tags:
        - Ask
        - Issuer
        - To
        - Notify
        - The
        - Shopper
        - Permits
        - Disable
        - Recurring
        - Details
        - Shopper
      summary: Ask issuer to notify the shopper
      description: >-
        Sends a request to the issuer so they can inform the shopper about the
        upcoming recurring payment. This endpoint is used only for local
        acquiring in India. For more information, refer to [Recurring card
        payments in
        India](https://docs.adyen.com/payment-methods/cards/cards-recurring-india).
  /scheduleAccountUpdater:
    post:
      tags:
        - Schedules
        - Running
        - The
        - Account
        - Updater
        - Permits
        - Disable
        - Recurring
        - Details
        - Shopper
        - Account
        - Updater
      summary: Schedule running the Account Updater
      description: >-
        When making the API call, you can submit either the credit card
        information, or the recurring detail reference and the shopper
        reference:

        * If the card information is provided, all the sub-fields for `card` are
        mandatory.

        * If the recurring detail reference is provided, the fields for
        `shopperReference` and `selectedRecurr
