openapi: 3.1.0
info:
  x-publicVersion: true
  title: Report Webhooks
tags:
  - name: General
webhooks:
  balancePlatform.report.created:
    post:
      tags:
        - General
      summary: Report generated
      description: >-
        Adyen sends this webhook after a report is generated and ready to be
        downloaded. The webhook contains the URL at which the report can be
        downloaded.


        Before you download reports, ask your Adyen contact for your report
        credentials. You must use your the credentials to authenticate your GET
        request.
      operationId: post-balancePlatform.report.created
      x-sortIndex: 0
      x-methodName: reportGenerated
      security:
        - BasicAuth: []
      requestBody:
        content:
          application/json:
            examples:
              balancePlatform.report.created:
                $ref: >-
                  #/components/examples/post-balancePlatform.report.created-balancePlatform.report.created
            schema:
              $ref: '#/components/schemas/ReportNotificationRequest'
      responses:
        '200':
          content:
            application/json:
              examples:
                balancePlatform.report.created:
                  $ref: '#/components/examples/WebhookAck'
              schema:
                $ref: '#/components/schemas/BalancePlatformNotificationResponse'
          description: OK - the request has succeede
