openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Stored Value API
x-groups:
  - General
tags:
  - name: General
paths:
  /changeStatus:
    post:
      tags:
        - Changes
        - The
        - Status
        - Of
        - Payments
        - Methods
        - Status
      summary: Changes the status of the payment method.
      description: >-
        Changes the status of the provided payment method to the specified
        status.
  /checkBalance:
    post:
      tags:
        - Checks
        - The
        - Balances
        - Status
        - Balance
      summary: Checks the balance.
      description: Checks the balance of the provided payment method.
  /issue:
    post:
      tags:
        - Issues
        - New
        - Cards
        - Status
        - Balance
        - Issues
      summary: Issues a new card.
      description: Issues a new card of the given payment method.
  /load:
    post:
      tags:
        - Loads
        - The
        - Payments
        - Methods
        - Status
        - Balance
        - Issues
        - Load
      summary: Loads the payment method.
      description: Loads the payment method with the specified funds.
  /mergeBalance:
    post:
      tags:
        - Merge
        - The
        - Balance
        - Of
        - Two
        - Cards
        - Status
        - Balance
        - Issues
        - Load
      summary: Merge the balance of two cards.
      description: >-
        Increases the balance of the paymentmethod by the full amount left on
        the source paymentmethod
  /voidTransaction:
    post:
      tags:
        - Voids
        - Transactions
        - Status
        - Balance
        - Issues
        - Load
        - Transactions
      summary: Voids a transaction.
      description: Voids the
