openapi: 3.1.0
info:
  x-publicVersion: true
  title: Adyen Test Cards API
  x-timestamp: '2022-05-03T09:24:07Z'
x-groups:
  - General
tags:
  - name: General
paths:
  /createTestCardRanges:
    post:
      tags:
        - Creates
        - One
        - Or
        - More
        - Tests
        - Cards
        - Ranges
        - Tests
        - Cards
        - Ranges
      summary: Creates one or more test card ranges.
      description: null
